Precommit with unit tests
vantihovich/go_tasks pull request #31
Opened 2022-08-09 10:21 UTC by vantihovich

2022-08-09 13:00 UTC, apaliavy requested changes

2022-08-09 13:00 UTC, apaliavy commented on swagger/configuration/configs_test.go
> +	assert := assert.New(t)
Why do you need it ?

2022-08-09 13:00 UTC, apaliavy commented on swagger/configuration/configs_test.go
> +		{P1: "my_secret_key", P2: 15},
What is the purpose of looping over slice with single element?

2022-08-09 13:00 UTC, apaliavy commented on swagger/configuration/configs_test.go
> +func MustGet() JWTParameters {
`MustGet` is not descriptive

2022-08-09 13:00 UTC, apaliavy commented on swagger/configuration/configs_test.go
> +		panic(err)
Don't panic

2022-08-09 13:00 UTC, apaliavy commented on swagger/configuration/configs_test.go
> +		assert.Equal(tt.P1, MustGet().SecretKey, "check secret")
Why do you need to call MustGet() twice? 
You can do something like 
```
cfg := MustGet()
asssert... 
```

2022-08-09 13:00 UTC, apaliavy commented on swagger/gmailsmtp/smtp_test.go
> +		{receiver: "vadim.antikhovich@gmail.com"},
Please format it properly

2022-08-09 13:00 UTC, apaliavy commented on swagger/gmailsmtp/smtp_test.go
> +	if err != nil {
`require.NoError(t, err, "message here")`

2022-08-09 13:00 UTC, apaliavy commented on swagger/gmailsmtp/smtp_test.go
> +		assert.NoError(smtp.SendForgottenPasswordEmail(t.receiver, cfgJWT.SecretKey), "check no error when sending email")
Does it mean that you are sending real emails from your tests? 🙀

2022-08-09 13:41 UTC, apaliavy commented on swagger/gmailsmtp/smtp_test.go
> +	if err != nil {
require.NoError(t, err, "message here")

2022-08-09 13:41 UTC, apaliavy commented on swagger/gmailsmtp/smtp_test.go
> +		receiver string
If you wanna try to write table tests, I'd expect to see here some additional fields like: 
- `input`
- `expectedResult`
- `expectError`
- `expectedError`
So underlying test function uses provided input and can properly handle the result. 

In this case I don't see any reasons to use this construction. Could you please explain, from your point of view?

2022-08-09 13:41 UTC, apaliavy commented on swagger/jwtgeneration/jwtgeneration_test.go
> +	if err != nil {
require.NoError(t, err, "message here")

2022-08-09 13:41 UTC, apaliavy commented on swagger/configuration/configs_test.go
> +package config
We often use `_test` suffix here, to test only public package interface

2022-08-09 13:42 UTC, apaliavy commented on swagger/mailjet/mailjet_test.go
> +	if err != nil {
require.NoError(t, err, "message here")

2022-08-12 15:29 UTC, vantihovich commented on swagger/configuration/configs_test.go
> +	assert := assert.New(t)
removed

2022-08-12 15:29 UTC, vantihovich commented on swagger/configuration/configs_test.go
> +		{P1: "my_secret_key", P2: 15},
removed loop

2022-08-12 15:30 UTC, vantihovich commented on swagger/configuration/configs_test.go
> +func MustGet() JWTParameters {
renamed

2022-08-12 15:31 UTC, vantihovich commented on swagger/configuration/configs_test.go
> +		panic(err)
Yes, Sir !!! 
No panic, Sir !!!
)))

2022-08-12 15:31 UTC, vantihovich commented on swagger/configuration/configs_test.go
> +		assert.Equal(tt.P1, MustGet().SecretKey, "check secret")
done

2022-08-12 15:36 UTC, vantihovich commented on swagger/gmailsmtp/smtp_test.go
> +		{receiver: "vadim.antikhovich@gmail.com"},
not actual after amendment

2022-08-12 15:36 UTC, vantihovich commented on swagger/gmailsmtp/smtp_test.go
> +	if err != nil {
done

2022-08-12 15:38 UTC, vantihovich commented on swagger/gmailsmtp/smtp_test.go
> +		assert.NoError(smtp.SendForgottenPasswordEmail(t.receiver, cfgJWT.SecretKey), "check no error when sending email")
after amendments smtp server is mocked and doesn`t touch real emails

2022-08-12 15:38 UTC, vantihovich commented on swagger/gmailsmtp/smtp_test.go
> +	if err != nil {
done

2022-08-12 15:40 UTC, vantihovich commented on swagger/gmailsmtp/smtp_test.go
> +		receiver string
Don`t see any reasons either. Thanks for clarifying table tests

2022-08-15 10:03 UTC, vantihovich commented on swagger/jwtgeneration/jwtgeneration_test.go
> +		{23},
removed table test, made test for validating JWT for one userID only

2022-08-26 15:11 UTC, vantihovich commented on swagger/configuration/configs_test.go
> +package config
added to package name "_test"

2022-08-26 15:12 UTC, vantihovich commented on swagger/jwtgeneration/jwtgeneration_test.go
> +	if err != nil {
done

2022-08-26 15:15 UTC, vantihovich commented on swagger/mailjet/mailjet_test.go
> +	if err != nil {
not actual after amendments,  also mailjet service is mocked and doesn`t touch real emails .

2022-08-29 12:37 UTC, apaliavy commented on swagger/gmailsmtp/smtp_test.go
> +		require.NoError(t, err, "failed to start mocking smtp")
if err != nil => then require.NoError? Something is wrong here :D

2022-08-29 12:37 UTC, apaliavy commented on swagger/jwtgeneration/jwtgeneration_test.go
> +	if err != nil {
Same strange thing again

2022-08-29 12:37 UTC, apaliavy commented on swagger/jwtgeneration/jwtgeneration_test.go
> +	userID := 23
Where it comes from?

2022-08-29 12:37 UTC, apaliavy commented on swagger/jwtgeneration/jwtgeneration_test.go
> +type claims struct {
Why do you need to re-define it here?

2022-08-29 12:37 UTC, apaliavy commented on swagger/jwtgeneration/jwtgeneration_test.go
> +func validate(token string, jwtParams cnfg.JWTParameters) bool {
Why do you have a validation function in tests?

2022-08-29 12:37 UTC, apaliavy commented on swagger/mailjet/mailjet_test.go
> +	smtpClientMocked := mailjet.NewSMTPClientMock(true)
Where it comes from?

2022-08-29 12:37 UTC, apaliavy commented on swagger/mailjet/mailjet_test.go
> +		StatusCode: 200,
`http.StatusOK`

2022-08-29 13:49 UTC, vantihovich commented on swagger/configuration/configs_test.go
> +	var tests = struct {
Made just two new variables to compare the results of loading with.

2022-08-29 14:43 UTC, vantihovich commented on swagger/gmailsmtp/smtp_test.go
> +		require.NoError(t, err, "failed to start mocking smtp")
Definitely wrong) Fixed by using t.Errorf()

2022-08-29 14:49 UTC, vantihovich commented on swagger/jwtgeneration/jwtgeneration_test.go
> +	if err != nil {
fixed

2022-08-29 15:30 UTC, vantihovich commented on swagger/jwtgeneration/jwtgeneration_test.go
> +type claims struct {
Fixed - just made it "exported" from tested package

2022-08-29 15:35 UTC, vantihovich commented on swagger/jwtgeneration/jwtgeneration_test.go
> +func validate(token string, jwtParams cnfg.JWTParameters) bool {
I need to know that the generated token is valid somehow. The question here is about the reusage of the existing validator?

2022-08-29 15:41 UTC, vantihovich commented on swagger/mailjet/mailjet_test.go
> +	smtpClientMocked := mailjet.NewSMTPClientMock(true)
This is just a "stub" from the mailjet`s package, it`s not used anywhere, using it as  mailjet.NewClient() needs at least  two arguments(two "clients" - http and smtp).

2022-08-29 15:43 UTC, vantihovich commented on swagger/mailjet/mailjet_test.go
> +		StatusCode: 200,
changed

2022-08-29 16:03 UTC, vantihovich commented on swagger/jwtgeneration/jwtgeneration_test.go
> +	userID := 23
I need an integer for unit testing , as the package has no specific requirements for userID field I`m just using the first one that comes in mind. If the question is about using "real test userID" , reproducing the whole cycle from the point of creating the concrete userID , or retrieving some userID from database looks a bit bulky for checking just a token generation. On the over hand when retrieving the concrete userID from DB the question might appear :why exactly this user?
Please specify what  is the better solution for such case.

2022-08-30 10:20 UTC, apaliavy commented on swagger/gmailsmtp/smtp_test.go
> +		require.NoError(t, err, "failed to start mocking smtp")
You made it even worse 😓 
```
err := server.Start()
require.NoError(t, err, "failed to start server")
```

2022-08-30 10:20 UTC, apaliavy commented on swagger/jwtgeneration/jwtgeneration_test.go
> +	if err != nil {
see comment above

2022-09-02 16:13 UTC, diskordanz commented on swagger/configuration/configs_test.go
> +	}
require.NoError asserts that a function returned no error, no need to check whether is err is nil or not

2022-09-02 16:13 UTC, diskordanz commented on swagger/configuration/configs_test.go
> +
please get rid of unnecessary empty lines across the files

2022-09-02 16:13 UTC, diskordanz commented on swagger/gmailsmtp/smtp_test.go
> +	if err != nil {
the same with require.NoError - there is no need for `if err != nil` check

2022-09-02 16:13 UTC, diskordanz commented on swagger/jwtgeneration/jwtgeneration_test.go
> +	if err != nil {
just `require.NoError(t, err, "message here")`
no need for `if err != nil` check

2022-09-02 16:13 UTC, diskordanz commented on swagger/jwtgeneration/jwtgeneration_test.go
> +	userID := 23
I'd suggest to rename this variable to mockUserID then

2022-09-02 16:13 UTC, diskordanz commented on swagger/jwtgeneration/jwtgeneration_test.go
> +func validate(token string, jwtParams cnfg.JWTParameters) bool {
not sure about the context but using token validation here you're assuming that GetToken function could return an invalid token. so from my point of view if you really need to validate the token it's better to use it inside the function itself

2022-09-07 10:20 UTC, diskordanz commented on swagger/jwtgeneration/jwtgeneration_test.go
> +	if err != nil {
please fix it

2022-09-16 10:21 UTC, vantihovich commented on swagger/gmailsmtp/smtp_test.go
> +		require.NoError(t, err, "failed to start mocking smtp")
done

2022-09-16 10:22 UTC, vantihovich commented on swagger/jwtgeneration/jwtgeneration_test.go
> +	if err != nil {
done

2022-09-16 12:07 UTC, diskordanz approved these changes

2022-09-20 12:12 UTC, merged